[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "/opt/build/repo/frontend/build"

[functions]
  directory = "netlify/functions"

[env]
  VAPID_PUBLIC_KEY = "your_vapid_public_key"
  VAPID_PRIVATE_KEY = "your_vapid_private_key"