[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/build"

[functions]
  directory = "netlify/functions"
  included_files = ["server/**"]

[env]
  VAPID_PUBLIC_KEY = "your_vapid_public_key"
  VAPID_PRIVATE_KEY = "your_vapid_private_key"